image: continuumio/anaconda3:latest

before_script:
  - if ! [[conda env list | grep -q 'emu-conda']]; then
  - conda env create -f environment.yml
  - fi;
  - source activate emu-conda
  - export EMU_DATABASE_DIR=./emu_database

test1:
  stage: test
  script:
    - python emu abundance example/full_length.fa

test2:
  stage: test
  script:
    - python emu abundance --type sr example/short_read_f.fq example/short_read_r.fq

test3:
  stage: test
  script:
    - python emu abundance --type sr example/short_read_f.fq

